project_id = "zienifzedhpcynuozfan"

[functions.send-push-notification]
verify_jwt = true

[functions.google-drive-sync]
verify_jwt = true

[functions.sync-drive-albums]
verify_jwt = false

[functions.sync-event-registration]
verify_jwt = false